name: Changelog Update

on:
  pull_request:
    types:
      - closed

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v3 # Updated to latest version
        with:
          python-version: 3.8

      - name: Update Changelog
        run: |
          echo "${{ github.event.pull_request.body }}" | python parse_pr.py >> CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "Update Changelog"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
